# curl -X GET "localhost:9200/_search?pretty" -H 'Content-Type: application/json' -d'
#{
#  "query": {
#    "fuzzy": {
#      "user.id": {
#        "value": "ki"
#      }
#    }
#  }
#}
#'
GET localhost:9200/_search?pretty
Content-Type: application/json


{
  "query": {
    "fuzzy": {
      "user.id": {
        "value": "ki"
      }
    }
  }
}


###



